### ISSUE TITLE
Pods crashing on Anthos on VMWare clusters

### ISSUE THREAD

**Issue by ameer00** [theemadnes/gke-whereami#3]
I downloaded the repo and am deploying the `k8s` folder as-is on Anthos on VMWare clusters and they are crashing with the following log message:

```google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started```

**Comment by theemadnes** [comment]
this was due to using an older version of the image
